### ISSUE TITLE
Ubuntu 16.04 `xsel` to primary keyboard not working

### ISSUE THREAD

**Issue by alphaCTzo7G** [tmux-plugins/tmux-yank#110]
I am using `VIM`, `tmux`, `zsh` combination.  

I have vim set clipboard set to `autoselect`, so I have made sure that the selection in VIM is transferred to the `*` register. I can see it if I pull up the `quickfix` window. When I use `xsel` in the terminal, I can get the correct output as well.

However, when I use `Ctrl+B+]` or `Ctrl+B+]+Shift+y` or `Ctrl+B+Ctrl+y` or `Ctrl+B+y`, nothing pastes the clipboard into the terminal or to vim. 

The docs are a bit confusing as to what is the correct method to paste from primary clipboard to the terminal.

Weirdly, if I do select and copy text from the terminal, I can paste it in vim or else where.

For example if I select a block of text using the `tmux-copy` plugin using `ctrl+b+ctrl+f`, I can use `xsel` to check whether the text is in the primary clipboard..

I can also use "*p" to paste it in VIM.

Any idea what I am doing wrong?

**Comment by alphaCTzo7G** [comment]
I do see the echo `xsel -i --$xsel_selection"` command in the `helpers.sh` file, but I dont see anything like `xsel-o-$xsel_selection`.

How does tmux_yank paste the `primary` or `clipboard` data into the shell or into another application?

**Comment by alphaCTzo7G** [comment]
I had to add the following command into my `.tmux.conf` to paste from xsel into the tmux buffer and then into the shell.
**bind-key C-p run-shell "xsel | tmux load-buffer - ; tmux paste-buffer"
**

It would be great if this could be incoroporated into tmux-yank..

**Comment by docwhat** [comment]
Note that `tmux-yank` only does copying.  It doesn't support pasting; that is part of tmux already.

You may not need `tmux-yank` at all, if you meet these requirements: [Linux with TMUX 1.5 or newer](https://github.com/tmux-plugins/tmux-yank#linux)

Otherwise, read [this section](https://github.com/tmux-plugins/tmux-yank#default-and-preferred-clipboard-programs) of the `README`.  You can use `@override_copy_command` or `@yank_selection` to try different things.
