### ISSUE TITLE
Line yank feature: don't "yank" a line if it's empty

### ISSUE THREAD

**Issue by bruno-** [tmux-plugins/tmux-yank#17]

**Comment by lafrenierejm** [comment]
Can you elaborate on what the title means?

**Comment by docwhat** [comment]
I think he means given the output of the following command:

``` sh
$ echo 'one' ; echo ; echo 'two'
one

two
```

That if you try selecting and copying the line between `one` and `two` that it doesn't actually send it to the clipboard copy command (e.g. `pbpaste`).

Not sure if it is a useful feature or not... I'd rather it just copies whatever I tell it to, even if it is inane, instead of trying to be "smart".

**Comment by docwhat** [comment]
I'm going to close.

I think "not yanking" when asked to do a yank is contrary to use expectation.

Plus, new management; I have to feel powerful somehow. 😜
