### ISSUE TITLE
Ignore RPROMT

### ISSUE THREAD

**Issue by justmytwospence** [tmux-plugins/tmux-yank#21]
ZSH (and presumably other shells) has the option to specify RPROMPT, a right-aligned prompt. Currently tmux-yank will yank this along with the actual contents of the line. Might there be a simple way to trim right-aligned content from the yanked line?

**Comment by TomasTomecek** [comment]
any luck? (hit this today)

**Comment by bruno-** [comment]
Hey, unfortunately no progress on this.

> There is definitely some way to hide the RPROMPT, because by default it disappears when your typed input is long enough to "hit" it

If someone can provide more info on how RPROMPT can be manipulated (basically we want to hide it) that would definitely help.

**Comment by TomasTomecek** [comment]
I've just tried something like this:
```shell
main() {                                                                                                                                                                                    
    unset RPROMPT                                                                                                                                                                           
    get_tmux_copy_mode                                                                                                                                                                      
    yank_current_line                                                                                                                                                                       
}   
```
But it didn't work. I guess that we need to get RPROMPT content directly from zsh.

**Comment by bruno-** [comment]
Hmm.. It's a good idea, but I think in this case `RPROMPT` is only "unset" for the current process (which is tmux_yank script I presume). `RPROMPT` is not unset for the `zsh` process which actually displays the right prompt.

**Comment by TomasTomecek** [comment]
yeah, and I think that even if one unsets the variable, zsh still needs to render the prompt -- so plain unsetting is just not enough. That's why I think that there should be some way to get prompt information directly from zsh.

**Comment by bruno-** [comment]
> That's why I think that there should be some way to get prompt information directly from zsh.

That would be useful, please let us know if you find anything about this.

**Comment by zakkak** [comment]
The corresponding code hiding RPROMPT in zsh can be found [here](http://sourceforge.net/p/zsh/code/ci/master/tree/Src/Zle/zle_refresh.c#l1593).  Unfortunately, It does not help much.

**Comment by yorkbai** [comment]
Great plugin!    I add some setting in ~/.zshrc like following , so display vi-mode infomation  at command line end.( such as: [INSERT] or [NORMAL] ...) , when am using prefix+y , it being copy to system clipboard with normal content in command line. plz help !

#.zshrc
VIMODE='-- INSERT --'
function zle-line-init zle-keymap-select {
    VIMODE="${${KEYMAP/vicmd/[NORMAL]}/(main|viins)/[INSERT]}"
    zle reset-prompt
}
zle -N zle-line-init 
zle -N zle-keymap-select

**Comment by joaosa** [comment]
I am also experiencing this. Any news? :)

**Comment by grodzik** [comment]
I made a proof-of-concept solution, but it requires user to insert some special invisible character in front of RPROMPT. This way it's possible to easily cut out RPROMPT from that sign till end of line (and eventually whitespaces in front of it). This idea was inspired by [this link](https://github.com/wincent/wincent/blob/7537a6db15d5b8e62560be5ffab31908191e8ac3/roles/dotfiles/files/.zshrc#L96)

    diff --git a/yank.tmux b/yank.tmux
    index 0529e76..4a8c1d3 100755
    --- a/yank.tmux
    +++ b/yank.tmux
    @@ -8,7 +8,7 @@ source "$HELPERS_DIR/helpers.sh"

    clipboard_copy_without_newline_command() {
            local copy_command="$1"
    -       echo "tr -d '\n' | $copy_command"
    +       echo "sed 's/[ ]* [^$]\\+//' | tr -d '\n' | $copy_command"
    }

    set_error_bindings() {

    There's a nbsp sign -----^

Making it as diff here, because it probably requires some configuration variable or `if-else` that I'm not aware of

**Comment by joaosa** [comment]
@grodzik seems like a good approach :) 

I'm having some trouble implementing this with [prezto](https://github.com/sorin-ionescu/prezto) with the [git module](https://github.com/sorin-ionescu/prezto/tree/master/modules/git) enabled though, as it seems RPROMPT gets rewritten

**Comment by docwhat** [comment]
So the short answer is "this is not possible".

The long answer is "maybe"...

The `RPROMPT` is specific to the running `zsh`.  You can _guess_ what it might be from another `zsh` process, but you won't be certain.

It might be possible to send a signal to the running `zsh` if you can figure out its pid and setup the running `zsh` to turn off the `RPROMPT` for a moment via a `trap` or something similar.

But that would be a very user-specific setup.

Maybe just add a `hook` to tmux-yank that gets run before/after entering copy mode?  The users can do this kind of trickery themselves?

Otherwise, use rectangle copy mode to avoid the `RPROMPT`?

**Comment by yorkbai** [comment]
I using alfred's pb plugin to edit clipboard for this issue  a long time.   recently  I using hammerspoon find another solve method. only add the following config in init.lua ,  we can using "ctrl + command +v" to paste the content not include [INSERT]. 
```
hs.hotkey.bind({"cmd", "ctrl"}, "V", function() hs.eventtap.keyStrokes(string.gsub(hs.pasteboard.getContents(), "%s*%[INSERT%]", "")) end)
```
