### ISSUE TITLE
My OS X doesn't seem to need reattach-to-user-namespace

### ISSUE THREAD

**Issue by unphased** [tmux-plugins/tmux-yank#31]
Please correct me if I'm wrong, but if I'm already in tmux (I'm running some 2.0 commit from git from about 3 weeks ago) and I run `echo "foo" > pbcopy` and my pastebuffer becomes properly populated with `foo`, doesn't that mean that I am not in need of using reattach-to-user-namespace?

It's just that when I try the `y` in copy-mode I get "Error! tmux-copy dependencies not installed!"

**Comment by bruno-** [comment]
Hey, thank you for reporting this.
I just tried uninstalling `reattach-to-user-namespace` and things worked for me too.

If I remember correctly, at the time this plugin was written things wouldn't work if `reattach-to-user-namespace` wasn't present. The dependency was added at that time.

I'm a little afraid to say that program is not needed anymore. In part, it's because I don't fully understand how it works.

If you don't want to install the `reattach-to-user-namespace`, for now please consider manually removing the dependency from these lines: https://github.com/tmux-plugins/tmux-yank/blob/master/yank.tmux#L14-15

I'd appreciate feedback from other users. If it turns out things work without `reattach-to-user-namespace` I'd be glad to drop that dependency.

**Comment by unphased** [comment]
Cool, yeah my current Macbook came with Lion and I know that paste didnt work properly back then, but it seems that somewhere in between, the behavior has been changed.

**Comment by bruno-** [comment]
Yea, and [this user also commented](https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/issues/32#issuecomment-68024665) his pbcopy works without `reattach-to-user-namespace`.

**Comment by bosr** [comment]
Same for me, I removed the dependency and yanking still works perfectly (Yosemite 10.10.3).

**Comment by bruno-** [comment]
@bosr submitted a pull request #32 that makes `reattach-to-user-namespace` optional and uses it only if it's installed.
The readme now indicates that things might work without it.

Let's leave this issue open in case someone wants to share more info about this.

**Comment by davidjb** [comment]
For note, I'm using Sierra (10.12.1) and the `reattach-to-user-namespace` is needed again so please don't drop support.  See https://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard/commit/c67238179ce456fa21b047c5ae22e9ac6a9310f6

**Comment by docwhat** [comment]
Can this be closed? It's updated in the README.md that `reattach-to-user-namespace` isn't (always) needed.

**Comment by docwhat** [comment]
Closing.  Moving discussion to #73
