### ISSUE TITLE
Can I redefine prefix-y to be prefix-<C-c> ?

### ISSUE THREAD

**Issue by statquant** [tmux-plugins/tmux-yank#64]
I use tmux+vim a lot and try to keep Ctrl+c and Ctrl-v to copy/paste to/from system buffer.
Can I redefine the prefix-y to be prefix-Ctrl+c ?

**Comment by bruno-** [comment]
Yea, you can override a binding by setting a `@yank_line` variable in your `.tmux.conf`:

    set -g @yank_line 'C-c'

Take a look at this file for variables for other bindings: https://github.com/tmux-plugins/tmux-yank/blob/master/scripts/helpers.sh

Btw. these variable names / options aren't documented because they are considered to be internal.. not a lot of ppl ask to change these.
